#!/bin/bash
set -euo pipefail

if ! [[ -x $(which mmc) ]]; then
    echo "$0: You must install the Mercury compiler first: brew install mercury" 1>&2
    exit 69 # EX_UNAVAILABLE
fi

if [[ $# -lt 1 ]]; then
    echo "usage: $0 N

Builds and runs the source file for day N,
The input for the day is supplied on stdin.

Example:

    $0 1" 1>&2
    exit 64 # EX_USAGE
fi

DAY=$1
DIR="src/"
if [[ $1 =~ day([0-9]+) ]]; then
    DAY=${BASH_REMATCH[1]}
    DIR=$(dirname "$1")
fi

cd "$DIR"
# XXX: Homebrew's build is not compiled in any grade that supports debugging. :(
mmc -E --use-subdirs -m day$DAY
"./day$DAY" < "../input/day$DAY.txt"
rm "./day$DAY"
