#!/bin/bash
set -euo pipefail

if ! [[ -x $(which mmc) ]]; then
    echo "$0: You must install the Mercury compiler first: brew install mercury" 1>&2
    exit 69 # EX_UNAVAILABLE
fi

if [[ $# -lt 1 ]]; then
    echo "usage: $0 N

Builds and runs the source file for day N,
The input for the day is supplied on stdin.

Example:

    $0 1" 1>&2
    exit 64 # EX_USAGE
fi

DAY=$1
DIR="src/"
if [[ $1 =~ day([0-9]+) ]]; then
    DAY=${BASH_REMATCH[1]}
    DIR=$(dirname "$1")
fi

cd "$DIR"
# XXX: Homebrew's build is not compiled in any grade that supports debugging. :(
CFILTER="cat"
if [[ -x $HOME/go/bin/cfilter ]]; then
    CFILTER="$HOME/go/bin/cfilter -f ../mmc.syntax"
fi
# To debug linking an executable, pass:  --link-executable-command="clang -v"
# To debug ALL the things, pass:     --verbose-commands
EXTRA_LIB_DIRS="/usr/local/Cellar/mercury/20.06/extras/lib/mercury" \
EXTRA_LIBRARIES="regex" \
mmc \
    --no-max-error-line-width \
    --output-compile-error-lines 128 \
    --use-subdirs \
    --make day$DAY 2>&1 | $CFILTER
"./day$DAY" < "../input/day$DAY.txt"
rm "./day$DAY"
