import re
from typing import Dict, NamedTuple
from collections import Counter

class Point (NamedTuple):
	east: int
	southeast: int
	
	def __mul__(self, other: int):
		return Point(self.east * other, self.southeast * other)
	
	def __add__(self, other):
		return Point(self.east + other.east, self.southeast + other.southeast)
	
	@staticmethod
	def from_dir(s):
		return MAP[s]

E = Point(east = 1, southeast = 0)
W = E * -1
SE = Point(east = 0, southeast = 1)
NW = SE * -1
NE = E + NW
SW = SE + W

MAP = {'e': E, 'w': W, 'se': SE, 'nw': NW, 'ne': NE, 'sw': SW}

example = """
sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew
"""

full_input = """
neenwnenwwnwnwnenwsesenwnwsenwnenwwnw
newnwnenenwnwneeneeswnwnwnenwneswsenwne
wenwswnwswwnenwnwnwwnwswenwneswnww
seneeswwneneneeneeneswneneneeswnee
swseswswneseswwenwneseswswswswnwsesesw
senwnwnwwwseneseenwnwsenwnwnenwnenwnw
seeneeseseseeeesesenweweseswesesese
nwwwnwnwwsenewsenwnwnwwwwwswew
swnwwsewnewwwsenenwnwwweweswwne
sweseseweseeesesenwenwseswsesenwewsw
neswwnwswnenenwsewwwnweneseenenwnw
eweeenweesweenweeeswneeeene
wswswswswweswsww
senesenwsenweneseneswwsenwswsewwsene
wnenwneenwneweeseneseneeseeneneenee
neeeeeeseseeeeeeewewneeeee
nwsewnwswnwnewsewwnwnweswwwnwwew
wnwnenesenenenwsenw
nenenenenewnenenenenwnenwnenenwnesenenese
senwwwswnwweewseswnewwewenwse
seswseseswswswswswnwswswseswswenwsesesw
eseneneneswnenewnenenenewsenenenwnene
nenwneneneneseenenenewsene
eseeenweeeneeeeeneee
nesesewseseneseseseseseswwsesewseesesee
swneseeseseseweneseseneneweseseswse
nenwneneneneenenenwneneneswsenw
eseesesewseseesenenwenwseseesewse
neweswswnwsenwwnesenwewseneseneseww
nenwneseweneseenenewnenewnenenewsw
senenwnwswnwnenwnwnwewnenwneenwnenwnw
wnwnwneseenewnwswwnwwewwsweww
esweneweewnewnewesweeeseeesene
nwnwnenenewnenenenenesenw
swwwswswswnewseenwwwseswswswwswwsw
seswswsesenwswswswnesweswswwswseswneswsw
swewswwneswswswwswswsw
wwseseneswewwswnwswwwnwwswswswnee
wnwwwwswnwnwnewnwwwnwwweenwsw
seseseswswswwswseseseseswneseswnesesew
seeseeseeswsenwnewseswswsewsewseswse
wweneeeneeneenenewneneneswsenene
enwwsewneneseeneneewesenwswwnwsw
nwwwnwnwnwnwnwwsenwwenwwwnwsewne
swswswseswswseswnwswnwsw
wswseneewswesenwwswnwswswwswnewswsw
seeeesenewnweeeseeesweenwseenee
seswnweesesewseseseswsenesesewsesenese
swneeneseenwnenwswenenwwseswswesenwe
swswnwsesenenwsenwsesesesesewswswsesenesw
swsesenweewsesesesesese
nwneeeeeseeeeesewseeseswwee
weeweeeenweswseeeeeseeee
ewwwwwnwwww
enwsweneeneeneseneneneeneswnewneese
wwswsewwwnwnwwnwnwsenwnwnwnwnwwne
seswsesweswwseswswwnwnwenenenwsenwnew
swwewnwswneswwseswwww
neneenewneneneneeeneneseweeneenee
nweneneeneeeeneneseneswneneenewnene
nesesenweneneswswswswwswswwenenwsww
swseeseseneseseseseswesesesesesesenwsese
senenewewnenenenewneswneene
nwnenenwnenesenesewsewnwsenewnwnwnee
nenenesenwwnenenenenwnenenenwne
seesenesesesesesesesesesesewseswsewse
swsenewswseswnwsewnesewwneseese
senwwnwnwnwwnwsenwwnwnwsenenenwswewnw
wseeswnwnwswnwnenwswseenwnewnwnwnew
nwwnwswnenwnwnwnwnwnwnwnweswnwwwnwnwnw
weswnwswweewneswwwwswwswnwsww
nwswswsenwnwnewwswsesweneewwneswe
nwwnwnwswnwenwnwwwswwwwwewwnwnww
nenenwnweneswneneseswenwneneswnewwneswne
swnenewneewneneneese
seeeeneeeseeenewnwwesweewse
neswsenewswswswsewswnesesewswswswswsw
nwnwwneneeswnwnwnwnwnwnwswnwnwnwwnwswnw
eswwnwnwnwenenwnwneswnenwnwnenwnenwnw
swnenenenwnenwnenewsweneneneneneneene
seseseseseswseseswsesesenwseenwseseswsese
eneseeswneneseeswnwsewwewenwnenew
eeenwnwsenwseesenweeweesweese
wnweseeseneseeeseseeswnwseseswsese
nwwswwseswswwswwwseneswwneswwwse
nwwseswneeseeneewsesesesewesesesese
wewwswseneswnwswswswwwswswnwswsew
nwnwnwnwnenwnenwnwnwnwenwnwnwnwnwneswswnw
nwweeeseseseenwneswswnwsenwnewswnwse
wnewwsenewwnwswnwswsesweeweswsw
nwneenwnwnwnewnwnwnwneswnwnwneswnenwnw
wswwswwswswswnwnwswwswweswwswew
nwsesenwsenwseseseseesewenwsewswseswe
swseseseseswwseseseseswswnewesw
nesenenwsenwesenwsesewneswseswsesesese
wwwswsewwnwewswwswnwwwswweneww
swswswswswswswswwswwswswswwneswsw
enwwwnwwwwwe
neneneeneneesenenwneswnenewnwnwneswnwne
swswnwswswneswnwswswswsweswswswswswswswse
nenwneneneeneneneswnewenewsenenewe
wswseenwnwwnwwnwwwwwnwwswenwne
swswswesenwseswswswwswwseswswnwsweswsw
wwwnewsenwwnwnwsewnwnwwnwnwnwsenewnw
eseseseseneesesesenesewseseseseseesw
wenwnwwnwwwwswewwwwenwwww
swenwnenenenwnwenewnwenwsweswneswnww
wwnwseweswsenwsesweseswseewswsenenesw
wnewwwwwwwwsewswsewswwwnesw
seeeeneneeneewe
eesesewseswswwwnesesenenesenwsesesw
wneswwnwnwnwnwenwnwswwwwwnwwnwwnw
seseseseeesenwswwsesesesesewe
nwnwnwwsewswwnwwwnwwnwenwenwnwwwnw
sewsenwwseswenwsenwsesenenesenwseseneswse
eeseeweseeseseeweseeneeeee
nwnwnwsenwnwnwwnenenwnenwswsewsenwnww
newnenenenenenenenenenewneeneseneneneswne
nwseswneesenwnwnwnwnesenwnwswneseneenw
wwseneneswwnesenwsesewwneneswwnww
wseesesenwseseseseesewsesenwseseesee
swwswwwwnwswwwwwsewwsewneswswne
swswsewswwwwwswwswnewsewwwwswne
nwnwnwnwswnenwnenenwnwnwnwnwnwnw
swseswswneswswswwswseswswswseswswswnesw
eeneneeneswneneneswneeneeenenenenwne
neswswswnwwwswwnwswswswwswweeswswsw
nwwwwswwenewswswwwnwnweswnweww
swsenewwswesewnwwnewneewwnewwse
wsenenwnwsenwwnwsewwnwwnwwneenw
swenenwnwnenwnwnenewnenenw
nwwenwwnwnwnwwnwswnwnwnenwnwwsewne
eseswsewseneswsenw
nwneeneneseenenenwwnwseswneneeneswnee
eneeeeeeswseeneweeenwseeenenee
nenwnenwnwnewneneneenwneswnenenenenene
nesenwwswsewnwnwewnwwswwnwwnwwenw
seesewseswswwseswnwwswseswseeesee
swwwwnwwswwweswswswsw
nenwnwnwnwnwnwnwnwnwnwsesenwnwenwswnwnwnw
swneneswnenenenenenenwsenwnenewnenwnwnwse
wneweeeeeeseeeseseseseseesesee
newnwneeewenwweswseseneswneeenwswe
seseseseeswswsesenesenewseswnenwwsenenw
wswwwnwswswsweewwwwswwwswswsw
swnenwnwneneseeeenenwwnenenenewnenwesw
nwwneneswseswnenwenwswnwnesewwsenwnwnwsw
swnenwswewsenwseewwnewswswnewwww
sesesesewesesesesenwneseseswseesesesese
wnwewwnewwwseswwwwswnewwww
swnwweeeneeeneneeee
swnenwneseswwswnwseneeswwnwwnenwnww
nenewnenenenewneneeenenwneneneenesw
enwenweswnenewesenwesweseeseweese
swewseswsweswswswswsewseseswseseswnesw
nesweenenwnweeneneneneseeneneeenewsw
nwnwnwnwwsenwnwnwnwnwnwnwnwnwnwnwnwnwe
swswswswswnwswesweswswswswnenwswswseswse
swsenenewwwnwwswnewwwseswswwswenese
nwsenwnwewwewwnwnwwnenwewnwnwse
swnenwnwwwswewnwnwseene
wwnwnwsenwnwnewnesenwnesenwwsewnwnww
nenenenenewneeneewseenwswneneneenee
senwseseseseseseswswseeseseswsese
nwnesenwnwnenewneneeswnenenwnenenenwnesw
seswwnenwenwwenwnwnwnwwwneswwwesew
neneeswwnenenenenenenenenenenenenewe
seseseseeswsenwswseseswseseswseneswswsw
enwnwsewsewneeeenenwseneeeneseene
nwewnwnenenenewneseenwnenenenenenewne
nwswneneneenenenesenwnenwnenenenenewnene
esweswnwswwswswwwwswswwswswesww
wwenesenwsenwwwnwnwswnwenwnwnwnwnw
seswwseseswseseseseswnwseneseseseswsesesw
eenewnwnwnwnenwnenenenwwnwnwnwnw
swwnwswswneneeswwswwwswwswswswsenese
nwswseseeseeseseseseseneeeneweesee
wswewswwswswnewswseswswewswswnwsene
nwneswnwnwneeneneneneneswnwnwnwnwnwnwnw
wwwwwwwewsewsenwnwwwwwwww
eewseseweseswsesesenwseneenwee
esweeneeeeweeeneneenee
eeeseenwseeseeeeswseeeneeese
eneneneneneeeeeeneneeeeneseesww
nweeeeneswenweeeeneneeneneswe
ewwnwsewwwwwwswnwnew
neseswswswseswseseswsewsenwsweseswswnwse
wwwwewwwnewwnwewsewsww
wwwswswnewwswwwswswsenwwswseswww
nwsesenwswsenwseswse
neneswenenenenwneneenewseneneneneene
wnweneeseeeeseeseseeseswneseesese
enewneesweeeeeseweeeeseenwnw
senwwnesweeseeeeeeeweneseseee
swwwwswwwswwswswwswneswswsw
seseseseseseneesesesesewse
swnwswsweenwswseswseswswswswswswswseswswse
nwwneeenwenenwneneswwsewseswnenwnwswne
nwwsenwsenweswswneeswswsw
swwswswswwswwewnewswswwswwswswsw
wwswwswswsenwwsw
seeeseseesewseeeeseewseesesese
eneeswweeeeeeeneesenwneseswnwesw
wnesewnwwnwnwsesenewwwnwenwnwnwwnw
swswswswwweswwwwwswswswwww
swsenwseneswnenewswswseneseswsee
seeswseseeseswswseswswswsesesesenwsesenwse
swweswwnwseswwnewswenewnesewwswnw
eenwseswnwseseseweseenesesesesesesesee
wwneeswwwwwsewwwwwwewwwww
wswseseswswseswswneswseswswneswsesenwwsee
seewwwwswswwwnwnwneswswsw
ewewswweesesesenwewesenwnwesese
nwnwnwnwewnwwnenwnwnwenwnwswnwsenwnw
newneeeneenewneneneenesenenwwenene
neeesweseeenwseseeseesesweswnwwse
wwwwwwswnewnwsewwwnwwwnwsewnw
nenenenesweneneneneneneenwnenewnwnene
enewsenenesenenenenenwneneneesesenwwne
nwnwenwnwnwneweewnwwsweenwsewne
wnwnwnwswwenwnwswewwnwnwnwnwnwnwnwwnw
nwneseenwnenwnenwswnwnwwnewneenenwenw
nweeweeewwnwneseenwswseseswnwsese
wswewswwwewnwnww
seswwsesenewwswnesesesweesesesesese
sweeenwnweeeesweeeeweswenw
nwnwnwnwsenwnwswnwswnwwnwnwnwnwsenenwe
wwewwswwwneswnwsewswwwwwswsw
swwwwwwwwwewnwwwwwwnw
sewwwswwwwwnwnwweswwwswwwwesw
nwwseneesenewswnwnenewwwesenwwnesene
nwswswnenenwnwnwnenenesenwswwnenwnenenw
nwnwnwnwnenwnwnwnewsenwnwnwnwnw
swswwseswswseswswsweseswswseseswsw
esesenweeeesewseseseseesenweswese
nwnwwswwwnwesewwneweswswnewnewww
swseseswneseeswsenwseseswseseswnwsesese
neneseseneenwswnenenwenenwnwswswnwnenwnw
nwnenenwsweneswnwnewswneneneswnenwnesese
nwsewnweenwnwneenwnwwsenwwsewnwnw
nwswwenwneneneneenwnwnwnesenenwnenwnw
seswnenenwnwwwnenweseswewnwwsesenw
neneseneneswneswnenenenwnwnwswnewnenenw
seesweeseeeseeeenwsesese
nwnenwenwnwnwnwnewnenwnwnwneswswnenw
seeeeeeeneeneseeweeeseeseewe
enenwwswnwnwnwwnenwwwsenwnwsenwnwsenwnw
wesenesewseseewse
nenesenenenenenwnenenewnenenwnwnesenenenw
neswnwswswwswswswneewnwweswnwwwwe
esewsenwweseseeseeweeewnewne
nwnwnenwwnwwnwswnenenenenesenwnwnenenwe
swseswnwswwwswswnenwnwswswesesewsenwnw
wesenwenwewwwwswnwneswwnenenwnw
seseseseseswsesesenwswseneseseseseseswwse
weenenewseswswneenenwwswwesesew
eneenenwnenenwnenenwewnwneneswnenwswnenw
swseswswseswswswswswswenwswswswseswnwswnwsw
eeeenwseeswneeesesw
nwneswswnenweneswnwwnwsewnweneenwwnw
eneneenenenwneswnwswnenwnwnenewnwnesene
swswsewswswswswswswneswsweewswwswswwne
wwwswwwwwwwwwswwswwnwneeww
seeseesesenwsenwseseseseseseseseswsesene
swnesweeeseswnwwnwneeenwnweee
nwwnewwwwsewwnwwnwneswnwwswesew
seseneeseeeseeseeseweeeswesene
seswwwseewnwswwwnwwswnewwswww
neeneneeneeenewneeseeeenesenw
wwnwwwwwnewnwwswwwwnww
sesenwseeseseseseseseseseseseseseseseswnw
neneeneeeneswneeneswnewenwwneee
nesenwneneneeseswsenenenenenenewnwenenwne
neenenenwnwsenesenwsenwnwswnenwne
swnwnwnweseseeeeeeeseseweswswseee
neneneneswnenenwneneneneneneeneneswnenene
newseneneenwnweweeeeseeeswew
eeeseeeeeeswseesenesesenwnwese
nwnewswnweneneneseenwswwnwswesesesene
neswesesesweenwseseeeeneseeeesee
eeesenweweeesenweseeeeswesesenw
seewesesenenwnewsewneeswnwsweesenw
nwwnesenwnenenwnenesenwnwnewnwnwnwnenw
sesenwseswseeseswnesweseseswnwwswseswsesw
nwneneneeswnwenwnwswnenwnenenw
eeseseseenewseswseswseeseneewee
swswsesesesewsenenwswweswswswsesenw
sewswswswswswswswneseswseswswsese
nesenenenwwnewneneneneseneseneeneswenene
nwswnwnwnwnwsenwneswwnewnesenenwneeneenw
swwwwwnwwewswnwwwwwenenwwsew
ewnwswswseenwsweeneneweeseenwwswne
nwseseswnwseseenwewseseseseseesesee
seeeseweseeeeeeneseeswseswsenw
wwewswneswswwwwwnesewwwswsww
nwnwwwnwwsewnwswnwewwnwnewwnww
swswswswseseswwswsesewswswswsweswnwnwene
nenwnwnwnwnwsenwnwnwnwnwnwwwnwnwnwsenwnw
nwswswnwnwsewsenwnwenwwnwnwnwnwnewnene
wswseeeswnwswseseneswesewswneswwsw
nwnwnwnwnenwnwswsenenwneeswsenenwnwswswnw
neewswneswnwseswnwnwnewnwwnwwwnw
nwnwseewneseneeeesewsesesee
nenesewnenenenenenenwne
seeseseseseswsesesesenwseseseswsesew
sewsenwwneneneeswseneeeeenenenwe
senwenwnwnwwenwnwnwnwnww
swnwsenwnwnwsenwswnenwnwswnwenenwnwsenene
seesenesesewsewnwnwswwsweenesewswsw
swenwnenewnenenwneswnwnenenewswnenee
wseesenwnwneswswsesesweswswseseswswswsw
eseseseseseseeseesesewseeseenwwee
eeneweseesweeeewneeewenenw
eeeneeswneeeneeeee
neneneeneswnwnenwnewnwneenewseenewew
eeswnwnenwnwneswnwnwwnwnwnwnwnw
swwswwwwwewswnwnwswsesw
seseseseswnwswseswne
sesesesenwnewenwnweseseseseeseseesew
wnesewwsewwwwwwnwsweswwnww
nwnenenwnewnenwnwseswneswnenenenenenwnwnwnw
nwseeswswswswswneseseswswswswswswsewswswsw
sesesewswneswseseseswseswsesesene
eseeseeseeeewsenwseeeeswsenwseese
eswswenenwnweenesenwsw
senwnwnwnwnwnenenwnenenwne
neswnwnwnwsenwnewnwnwneeewnenwswnenenenw
seeseeeseeneseswnewnewseeseeseesw
swswseswwswneswwswswswswweswswnenesw
eeenweseeseseeeeeseneeeswwe
nwnwnwnweeswnenwnenwnwnenwwnwswnwnewsene
neneswswwswneswswnewnwswswe
wwwwwwwweewsenwswwnwneswnwwsw
ewswseswnewsenwnwnwsenwnwsewseeseesw
sesesesenenwseswseswseseseseswwseswswe
neseweseseseseseseesewseseesesenese
nenenenenenesenewenenenwsewsenenene
weenesweseswesenwseeenwsese
weeseneseswswseswnwseseseesewnesesene
eeseneswswsweeeeseenwsenwsesenweew
swswnweswswswwseswswwwnwswwwwwswsw
seswswnwwnenwnenenwnwnwnwnwnwnwnw
swswseswswswswnwnwswswswsweswswseswswsw
ewswswswswswnwnenwswsesweswseswswswsww
nwwswwwwnewwwwnwnw
wnwewsenwwwwwwwwwewnewwww
swwsewwwwwwnenwnwwneewswwene
sweesweswwwneseswswnenwwseseewwse
swswwswneswweeswnwwenwswswseswswsw
nenwenenwswsenwnwswnenwenenwnwnwswswnenw
wwsewwwwnewwww
nweseeneeneswenesenwenwneneswnwne
esweswswswswseseswnwswswwswwnwwswnw
wwwsenwnewswwnwswwswwnwseseewwsw
seseswneswneseseswnenwswswswwseswswswse
swneeeneeneswnweneneneswswneneeneene
swswwswnwwnweeswswswwswwswswswswene
swswswwswswswswswnwneswswseswswswswswsw
seswwnwseswseswswswswsesesenewseseswsesene
enwnwseeneneeweneseeswnewnenewseene
nwswnesenwnewswswweenewewsesesesewne
enenwneseswneeneneenwneeenenesweee
nwnwseswnwnwwnwnwnwnenwnwnwnwnwnwnwnw
seseeseseseseeneweeeeweseseesee
enwnenwnwnewnwnwnenwenenwnwnwwnwnenw
eneseswnwnwnwnweswnwsewneswnwsenenenw
enenenwnwswnenenesenesewnenesene
eeneneeewseneneeeneswnee
seseswswseseswnwswenwswswswswseseeswsese
nwewswwwswnenesewwswwnwwwwewwsw
nwnwnwnweswnwnwnwnwnwnwnwnwnwnwnw
sewnenwnewnwneseneseswsenwnwnwswnenesesw
swswnwswwneeneewwewswswswnwwsew
newnenwnenwnwnwnwnenesenwnwwenwnwnwnw
wswwswwwwwswewwwwwnw
ewenweeesesesewseneseneeseswew
senewwswswsewnenwswewwwswwenenese
seswseeseseswesewseenweesenenesese
seeweseeneeeeeseenweeeewsee
neenweenewneesw
swnesenwsweeeswnwswwwseswneeswww
nwnwnwnenenweswsenwnwwneswnwnwnw
nesewswwwwewsww
seseseswseswswsesenwseswswswsesese
neenenenwneneeneenwswneneneneseneneene
nwnenwnwsewnwnenwnwnenenwnwnesenwnwnenwne
enenwneswwwnewswwswwswwwnwnesenese
seewenwseewswnesesesenwswswseswsewsw
swseswneswseseswswseswneswsenesesenwwsese
neneneewneneneneneneneseneswnwsenwneene
wnewewwwwwwsewsewwwwwneww
wswseeswsesesenwsesenwseseeswswswswse
eeenwswnwnesweeeeseeeeewesewe
swwwswwsesewwneenwswnenewsewwww
swswswswswseswswswswswneswsw
nwesewnwnwnwwnwnwnewnwnwwe
nwwwwneswwsesenesenwneenewwwwnw
seseswswswseneswswswswswnwswseseswsesewene
sweseseseseseeseseseseenwsesesesesesenw
swswnwswswswswswswwseswwnwswswswswswse
nenenenwnewsenenene
nwnwswwnwneeneswnwenesweswswwswe
nwnwnwnenwnenwnwneswneneswneneswnesenwswne
nwneseswswswswswseneswswwsesw
wnwswnwnwswswswswenenenwswswwsweswee
seswseseswseswseseeseswswneswswswswnwsese
seseneseseseseseesesesesesesesew
seseneswnwsesenwsesesewswseseswnw
nwswwnewwswwnewewwswesenwsww
swswswwseseseswwswswneswswswneswsweswsw
newnenenenwnenenwnwneeneswnenenwnenenw
swwswnweenewwsenwnenwenenweswsenwwne
seswnesesesenewseseseseseseswseswsewse
eseseeeeseeewwseesewsew
swswswswsweswswswswnwseswswwwswenenwsw
eswswswswswwswneseswswwswswswswwwsw
nenwswsenenwnenenenwnenenweswnenenw
swnwwewwwneeewwnwwswnwnwnenwsw
swwswseswswwswwwwswewnwsw
swwswewwswewnwnweewwnwneswwnw
senwnwseswswsesweswseeswwnwwesweswsw
wswnwwwwnwswwwwnewwswseswwsewsesw
swnwswswseswswswsesweseswseswsewsenwse
seswsenwswswnwswnwswswswenwewswswseene
eneweneswnwseeswneswwnwwsenwenww
eeeeenwswneseewseesenwewseneswse
nwnenwneneewnenenenwnenwnenwneseneseswnee
swneneewswswwswswewwswswnwnweswswe
sesesewseseseswseswsesesesesene
nwseeswseseweswswwe
nwnewnwewwwswwswwnwwwwswwnwe
wseneeeeneswweenwseeenwsewee
swsenwswseseswsesesenesesewwseneseswsese
seesesewsesesenewseseswseesenwsesesesese
swswsweseswnwswswswsesenw
neenwswswswswneneweswwneseeswneswsww
swwwsweswwnweswswwwnewwnwswwww
nwnwnwenenwnwneseswsenwsweswnwnwnewnw
wwwnewswwwswwwwwwwww
sweseseseseneneneseseseseseseseewwse
neeneeneeeweneneneseneneeenene
nwenwwwnwnwnwnwwnwnwnwsewnewnww
senwnwnwesweweewese
eseweeeeeseenweeeeeseewese
swneswsesesewswnwswseswneswseseee
neeseneeeneseeeenwswweeenenwnee
esweneenenwneeenesweeeeeeee
nwwwnwwwwwnwnwwwnwenewnwsewe
esenenweseeenweneneeneeneenenene
seeeeeeeeewenwseneeeeeee
swswnwwsenenwneneneneneseswenesenenew
senenwnewnwnwnenenwsenenwne
nenenwnewneneseneenenesenwnwneswnewne
sewswwneswwswwswewnwwswnwswwwsww
swswseswneswswwwswswnesewwwswswwwsw
swswneswwswwswswnwswwwswswswswseswe
nwenwwnwwnwnwnwswwnwwenwnwenwnww
swseswswswswwwnweswenw
senweswseseseswswswswseseswswwseswsese
neewwwnwnwwsenewsweswwnwswsesew
swseswseswneswseseseseseseseswnesesewswsw
wwwneenwwnwnwwneswwswnwsenwwnwswnw
neseseswwneseseseseswnwseswseswwseswsesw
nenenenenewwneeswweneeswweenwe
sweeswswswswswwwseseesenww
neneseneeswnewnwnewwsenwneneseenenene
nwnwsenwnenwnwnenwsenenwswnwnwnenwnwnwne
eeeeeeeswweeseneneeeeeneeenw
nenwnwsenwnenwnwwnwnwwnwnwnenwnwsenwnwnwnw
enwwseenwnwswsenwnwnwnwne
eeeeneneeeewseesweeeeeee
wnenwseweswnwnwnwwswewwnwnwnenwesw
eeneeweseeeneeseeneeeeweee
swnwnwenwwneseseesw
nwwwwswwwwwnwwnwnwwne
sewsweswenwnwneswwnenwnenewswesene
seeseeseswswneneeseswsesewswnwnwswsw
wseswnwnwnwseneenwsewsenwswew
wwneneswwswwswneswneseesenwwswsesw
wwwswnesenesewwwswswsewswswwwnw
nwnwswnwnwwwnwnwnwnwnwwnwnwnwewnwe
neneneneeswneneneneneneneneneene
ewseneseseseseeeseeseseseesesese
eeeeewnweseeesweewseeeeswnw
seswswswswwsweswswswswswswswsw
swswseseswwswsenwswswseswswseeseswswsw
swnwenwwwwwnwnewnenwswswenwsewnwnwnw
nwnwsenwnwswswwnwneenwnwseewnwsenwnese
enwnwnenwnwnwnenwnesenwswnenwnwnenenene
eswseswneenwenwnwseeewswseeneswnw
wwswnwswswswswseswswsweswswnewwsww
seeenwnenenenenesenenewneeenene
seswseseswswswswswseswswnwsw
nwswnwnesenenwneswnwnwnwnenwnwenwnwwnw
nweeseseswswswseswswseswseseseswnwseswsesw
eenweeeeeeneeeseeenwswnwese
swswswswswswswswsewnwswswswseswseswswswne
eswswnwnwnesweenwnwnww
neweseseneewsenweswsewseseeswwee
nwsenwenwnwnwwnwseswenwnwnwnwnenwwew
nwwnwnwwweseswnwww
swwewnwswswwwnenweewew
nwnwnwnwwnwswnenwsenenwwwnwsenwww
seeneseseeeeweweseenweseseswe
eesenwwewseesesenweeeseeenesw
swswswswswswswswswswswswnwswwswswswswee
wneneseneneesenenwneenenenwne
nenewneenenenenenenenenwnene
nesenwswnwnenwnwnwnenwswnwswnwnenene
nwwseneneneseneeenenenesweneneenwne
eseeenweesweeeeeneseeewenese
swwseseseswneswseseswswsweswsenwseswswse
seeeesenwswesewswnwseseseneenwwe
sweneeeweenenwneeeeeseseeseeew
neeswseweeeseseeeeneesenwsese
swwswwwswswswswswswswwneswwswswnese
senwneneswneeeswneneneseneneenwnewnenene
wwwwswwwwsewwwnww
ewswwwswswwswnwswwwwsewwwwnewsw
wnwswswnwneseseneesenenwsewnw
enwsweseeeeeeseneseseenweeeee
enewneeneeeeeneseeeeww
eweweneeseseeseseeeeeeeeee
swsenwweewwnwwnw
nenwseweneneseswnenwnewswneeew
eeswneneneseeneeseenewenwnweene
eeeeeeneneeesw
"""

RE = re.compile(r'(?:n|s)?(?:e|w)')

def tile_at(line: str) -> Point:
	steps = RE.findall(line)
	points = [Point.from_dir(d) for d in steps]
	tile = Point(0,0)
	for p in points:
		tile = tile + p
	return tile

def is_black(count):
	return count % 2 == 1

def black_tiles(counter):
	return [t for (t, count) in counter.items() if is_black(count)]

def black_count(c):
	return len(black_tiles(c))

input = full_input
#input = example

# def tiles(input: str) -> Dict[Point, bool]:
lines = input.strip().splitlines()
assert ''.join(RE.findall(lines[0])) == lines[0], "bad line parse"

tiles = [tile_at(pos) for pos in lines]
c = Counter(tiles)
black = black_tiles(c)
count = len(black)
from pprint import pprint
pprint(black)
pprint(count)
# Answer to part 1: 465
# Answer for example: 10

###
# Part 2: Game of Life, Again
def neighbors(p):
	return [p + other for other in MAP.values()]

def black_neighbors(around, counter) -> int:
	return len([n for n in neighbors(around) if is_black(counter[n])])

def should_flip(point, counter):
	nc = black_neighbors(point, counter)
	if is_black(counter[point]):
		if nc == 0 or nc > 2:
			return True
	elif nc == 2:
		return True
	return False

def with_frontier(next):
	ks = next.keys()
	all = set()
	for k in ks:
		all.add(k)
		for n in neighbors(k):
			all.add(n)
	return all

def step(counter):
	next = Counter(counter)
	keys = with_frontier(next)
	for p in keys:
		if should_flip(p, counter):
			next[p] += 1
	return next

def run(ndays, c):
	for i in range(ndays):
		c = step(c)
	return c

print(black_count(run(100, c)))
